# Generated by Django 3.1.5 on 2021-01-17 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shisetsu', '0002_auto_20210117_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='シフトID')),
                ('name', models.CharField(max_length=1, verbose_name='シフト名')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('wrok_time', models.IntegerField(verbose_name='勤務時間')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='スケジュールID')),
                ('date', models.DateField(verbose_name='日付')),
                ('shift_name_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_name1', to='schedule.shift', verbose_name='1シフト名')),
                ('shift_name_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_name2', to='schedule.shift', verbose_name='2シフト名')),
                ('shift_name_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_name3', to='schedule.shift', verbose_name='3シフト名')),
                ('shift_name_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_name4', to='schedule.shift', verbose_name='4シフト名')),
                ('shisetsu_name_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shisetsu_name1', to='shisetsu.shisetsu', verbose_name='1施設')),
                ('shisetsu_name_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shisetsu_name2', to='shisetsu.shisetsu', verbose_name='2施設')),
                ('shisetsu_name_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shisetsu_name3', to='shisetsu.shisetsu', verbose_name='3施設')),
                ('shisetsu_name_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shisetsu_name4', to='shisetsu.shisetsu', verbose_name='4施設')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
